version: 2

jobs:
  swift-3:
    docker:
      - image: swift:3.1
      - image: circleci/postgres:latest
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: ""
    steps:
      - run: eval "$(curl -sL https://apt.vapor.sh)"
      - run: apt-get install -yq libpq-dev ctls
      - checkout
      - run: swift build
      - run: swift build -c release
      - run: swift test

  swift-4:
    docker:
      - image: swift:4.0
      - image: circleci/postgres:latest
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: ""
    steps:
      - run: eval "$(curl -sL https://apt.vapor.sh)"
      - run: apt-get install -yq libpq-dev ctls
      - checkout
      - run: swift build
      - run: swift build -c release
      - run: swift test

workflows:
  version: 2
  tests:
    jobs:
      - swift-3
      - swift-4